### ISSUE TITLE
Nice work !

### ISSUE THREAD

**Issue by ycat3** [reppy4620/Dialog#10]
I added another Japanese around 2000 lines data to train more.
Also I added voice reply functionality.
https://jweb.asia/26-it/ai/51-bert-chatbot.html

**Comment by reppy4620** [comment]
Thank you so much for your great work and sorry for not good quality of generated conversation.

I think train data has biases due to the data collected with queries such as "おはよう", "疲れ", "それな" etc.... This is one of the reason that model has low diversities i.e. could not generate variety utterances and long sequences. Of course, model architecture and maximizing likelihood with cross-entropy loss are too.

By the way, can I mention the link of your work in README？

Thank you.

**Comment by ycat3** [comment]
Thank you quick reply.
Of course, you can link my work , and contact me since i am living in Yokohama.

**Comment by reppy4620** [comment]
I'm grad to hear that. I'll update README if I have free time.
Thanks again.
