### ISSUE TITLE
Question about the memory representation

### ISSUE THREAD

**Issue by kfj7elgjs** [reppy4620/Dialog#11]
Hello,

thank you for providing such an interesting project!
I have a question about the following lines:
https://github.com/reppy4620/Dialog/blob/b33fa575cb801a81704bac0fdaeb209d189f54e0/nn/model/encoder_decoder.py#L52-L53

I do not understand why the two source embeddings are concatenated.
What does this implementation mean?

thanks!

**Comment by reppy4620** [comment]
Thank you for letting me know.

These lines don't have any meanings because they were added for debugging.
I wanted to check that self attention can run if size of query are different from size of key and value, I think.
At least, my local project doesn't have those lines, so I don't know why this repo still remain them.
Therefore these lines actually have to be deleted.

I'll update soon.

**Comment by kfj7elgjs** [comment]
Thank you for the update!
